sudo: false
language: ruby

rvm:
- 2.6.0
- 2.5.3
- 2.4.5
- 2.3.8
- 2.2
- 2.1
- 2.0
- 1.9.3
- ruby-head
- jruby-head
- jruby-9.2.5.0
- truffleruby

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: 1.9.3
    - truffleruby
